# site info
title: WMI
subtitle: Website Manajemen Indonesia
# hexo default is empty, change to exact languages, and add xx.yml under your theme languages dir.
language: [id,en]
timezone: Asia/Jakarta
author: L3n4r0x

# permalink
url: https://www.webmanajemen.com
root: /hexo-multi-language/
## https://hexo.io/docs/permalinks#Multi-language-Support
new_post_name: :lang/:title.md # hexo new "Hello World" --lang tw => source/_posts/tw/Hello-World.md
permalink: :lang/:title.html # url will become http://localhost:4000/tw/hello-world.html
pretty_urls.trailing_html: true # keep .html extension
pretty_urls.trailing_index: false # keep trailing index.html
pretty_urls: true # rewrite permalink variables (https://hexo.io/docs/variables) to pretty url

# theme
theme: butterfly

# config hexo-generator-i18n option (optional, this is default option)
i18n:
  type: [page, post]
  generator: [archive, category, tag, index]

# config hexo-generator-index
index_generator:
  path: ''
  per_page: 10
  order_by: -updated
  pagination_dir: page

# config hexo-generator-category
category_generator:
  per_page: 10
  order_by: -updated

# config hexo-generator-tag
tag_generator:
  per_page: 10
  order_by: -updated

# config hexo-generator-archive
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -updated

# config hexo-deployer-git
deploy:
  type: git
  repo: https://github.com/dimaslanjaka/hexo-multi-language
  branch: gh-pages
  message: "chore: publish {{ now(\"yyyy-MM-dd HH:mm:ss\") }}"
  name: dimaslanjaka
  email: dimaslanjaka@gmail.com